GRANT SELECT ON * TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant_employment` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `pokket_user` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant_custody` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant_check_in` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant_plan_item` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `pokket_user_message_thread` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `document` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `announcement` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `notification` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `pokket_user_opt_out` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `case_note` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `pokket_user_permission` TO 'mypokketdbuser'@'%';
GRANT INSERT ON `device_tracking` TO 'mypokketdbuser'@'%';
GRANT INSERT ON `ui_log` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant_referral_document` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `agreement_executed_user` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `appointment_request` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `plan_template` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `plan_template_application` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `message_sentiment` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `participant_referral` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `video_meeting_attendance` TO 'mypokketdbuser'@'%';
GRANT INSERT, UPDATE ON `pokket_user_document` TO 'mypokketdbuser'@'%';
-- GRANT INSERT, UPDATE ON `appointment_settings` TO 'mypokketdbuser'@'%';